version: "3.9"

services:
  database: 
    image: postgres:14
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: ./webapp
    ports:
      - "3000:3000"
    environment:
      - PGHOST=database
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
    depends_on:
      - database